-- Book Affinity · esquema inicial para Supabase
-- Versión 0.1.0 · 05/08/2026
-- Ejecuta el script completo en Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.books (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  google_books_id text,
  title text not null check (char_length(trim(title)) > 0),
  subtitle text,
  authors text[] not null default '{}',
  description text,
  notes text,
  cover_url text,
  thumbnail_url text,
  isbn_10 text,
  isbn_13 text,
  publisher text,
  published_date text,
  language text,
  categories text[] not null default '{}',
  page_count integer check (page_count is null or page_count >= 0),
  current_page integer not null default 0 check (current_page >= 0),
  progress_percent numeric(5,2) generated always as (
    case
      when page_count is null or page_count = 0 then 0
      else least(100, round((current_page::numeric / page_count::numeric) * 100, 2))
    end
  ) stored,
  status text not null default 'want_to_read'
    check (status in ('want_to_read', 'reading', 'finished', 'paused', 'abandoned')),
  rating numeric(2,1) check (rating is null or (rating >= 0 and rating <= 5)),
  started_at date,
  finished_at date,
  added_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint books_page_progress_check check (page_count is null or current_page <= page_count),
  constraint books_finished_dates_check check (finished_at is null or started_at is null or finished_at >= started_at)
);

create unique index if not exists books_user_google_id_unique
  on public.books (user_id, google_books_id)
  where google_books_id is not null;

create index if not exists books_user_status_idx
  on public.books (user_id, status, updated_at desc);

create index if not exists books_user_title_idx
  on public.books (user_id, lower(title));

create table if not exists public.reading_updates (
  id bigint generated by default as identity primary key,
  book_id uuid not null references public.books(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  current_page integer not null default 0 check (current_page >= 0),
  status text not null
    check (status in ('want_to_read', 'reading', 'finished', 'paused', 'abandoned')),
  note text,
  recorded_at timestamptz not null default now()
);

create index if not exists reading_updates_book_date_idx
  on public.reading_updates (book_id, recorded_at desc);

create index if not exists reading_updates_user_date_idx
  on public.reading_updates (user_id, recorded_at desc);

create or replace function public.set_book_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists books_set_updated_at on public.books;
create trigger books_set_updated_at
before update on public.books
for each row execute function public.set_book_updated_at();

create or replace function public.log_book_progress()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'INSERT'
     or new.current_page is distinct from old.current_page
     or new.status is distinct from old.status then
    insert into public.reading_updates (book_id, user_id, current_page, status)
    values (new.id, new.user_id, new.current_page, new.status);
  end if;
  return new;
end;
$$;

drop trigger if exists books_log_progress on public.books;
create trigger books_log_progress
after insert or update of current_page, status on public.books
for each row execute function public.log_book_progress();

alter table public.books enable row level security;
alter table public.reading_updates enable row level security;

drop policy if exists "books_select_own" on public.books;
create policy "books_select_own"
on public.books
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "books_insert_own" on public.books;
create policy "books_insert_own"
on public.books
for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "books_update_own" on public.books;
create policy "books_update_own"
on public.books
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "books_delete_own" on public.books;
create policy "books_delete_own"
on public.books
for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "reading_updates_select_own" on public.reading_updates;
create policy "reading_updates_select_own"
on public.reading_updates
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "reading_updates_insert_own" on public.reading_updates;
create policy "reading_updates_insert_own"
on public.reading_updates
for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1
    from public.books
    where books.id = reading_updates.book_id
      and books.user_id = (select auth.uid())
  )
);

drop policy if exists "reading_updates_delete_own" on public.reading_updates;
create policy "reading_updates_delete_own"
on public.reading_updates
for delete
to authenticated
using ((select auth.uid()) = user_id);

revoke all on table public.books from anon;
revoke all on table public.reading_updates from anon;

grant select, insert, update, delete on table public.books to authenticated;
grant select, insert, delete on table public.reading_updates to authenticated;
grant usage, select on sequence public.reading_updates_id_seq to authenticated;

comment on table public.books is 'Biblioteca personal de cada usuario de Book Affinity.';
comment on table public.reading_updates is 'Historial automático de páginas y cambios de estado de lectura.';
comment on column public.books.progress_percent is 'Porcentaje calculado automáticamente a partir de current_page y page_count.';
