-- Book Affinity · lectores, publicaciones y comentarios
-- Migración 0.5.0 · 06/08/2026
-- Ejecuta este archivo completo en Supabase > SQL Editor.
-- Es idempotente: puede volver a ejecutarse sin borrar datos.

create extension if not exists pgcrypto;

-- El icono se replica en el perfil público para poder mostrarlo a otros lectores.
alter table public.book_affinity_profiles
  add column if not exists avatar_id text;

alter table public.book_affinity_profiles
  drop constraint if exists book_affinity_profiles_avatar_format;

alter table public.book_affinity_profiles
  add constraint book_affinity_profiles_avatar_format check (
    avatar_id is null
    or avatar_id in ('literary-crest', 'minimal-reader', 'moon-book', 'book-shield', 'retro-reader')
  );

update public.book_affinity_profiles as profile
set avatar_id = users.raw_user_meta_data ->> 'book_affinity_avatar'
from auth.users as users
where users.id = profile.user_id
  and profile.avatar_id is null
  and users.raw_user_meta_data ->> 'book_affinity_avatar' in (
    'literary-crest', 'minimal-reader', 'moon-book', 'book-shield', 'retro-reader'
  );

-- Cada libro es privado de forma predeterminada.
alter table public.books
  add column if not exists is_public boolean not null default false;

create index if not exists books_social_feed_idx
  on public.books (user_id, is_public, status, updated_at desc);

create table if not exists public.book_affinity_follows (
  follower_id uuid not null references auth.users(id) on delete cascade,
  followed_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, followed_id),
  constraint book_affinity_follows_not_self check (follower_id <> followed_id)
);

create index if not exists book_affinity_follows_followed_idx
  on public.book_affinity_follows (followed_id, created_at desc);

create table if not exists public.book_affinity_comments (
  id bigint generated by default as identity primary key,
  book_id uuid not null references public.books(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint book_affinity_comments_body_length check (
    char_length(trim(body)) between 1 and 1000
  )
);

create index if not exists book_affinity_comments_book_date_idx
  on public.book_affinity_comments (book_id, created_at asc);

create index if not exists book_affinity_comments_user_idx
  on public.book_affinity_comments (user_id, created_at desc);

create or replace function public.book_affinity_set_comment_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists book_affinity_comments_set_updated_at on public.book_affinity_comments;
create trigger book_affinity_comments_set_updated_at
before update on public.book_affinity_comments
for each row execute function public.book_affinity_set_comment_updated_at();

alter table public.book_affinity_follows enable row level security;
alter table public.book_affinity_comments enable row level security;

-- Las tablas sociales se usan únicamente mediante funciones controladas.
revoke all on table public.book_affinity_follows from anon, authenticated;
revoke all on table public.book_affinity_comments from anon, authenticated;
revoke all on sequence public.book_affinity_comments_id_seq from anon, authenticated;

create or replace function public.book_affinity_can_view_published_book(p_book_id uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1
    from public.books as book
    where book.id = p_book_id
      and book.is_public = true
      and (
        book.user_id = auth.uid()
        or exists (
          select 1
          from public.book_affinity_follows as follow
          where follow.follower_id = auth.uid()
            and follow.followed_id = book.user_id
        )
      )
  );
$$;

create or replace function public.book_affinity_set_my_avatar(p_avatar_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_avatar text := nullif(trim(coalesce(p_avatar_id, '')), '');
begin
  if v_user_id is null then
    raise exception 'Debes iniciar sesión para cambiar el icono.' using errcode = '42501';
  end if;

  if v_avatar is not null and v_avatar not in (
    'literary-crest', 'minimal-reader', 'moon-book', 'book-shield', 'retro-reader'
  ) then
    raise exception 'El icono seleccionado no existe.' using errcode = '22023';
  end if;

  insert into public.book_affinity_profiles (user_id, avatar_id)
  values (v_user_id, v_avatar)
  on conflict (user_id) do update
    set avatar_id = excluded.avatar_id,
        updated_at = now();

  return jsonb_build_object('user_id', v_user_id, 'avatar_id', v_avatar);
end;
$$;

create or replace function public.book_affinity_find_reader(p_username text)
returns jsonb
language plpgsql
security definer
stable
set search_path = public
as $$
declare
  v_username text := lower(trim(coalesce(p_username, '')));
  v_profile public.book_affinity_profiles%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Debes iniciar sesión para buscar lectores.' using errcode = '42501';
  end if;

  if v_username !~ '^[a-z0-9_]{3,24}$' then
    return null;
  end if;

  select * into v_profile
  from public.book_affinity_profiles
  where username_normalized = v_username;

  if not found then return null; end if;

  return jsonb_build_object(
    'user_id', v_profile.user_id,
    'username', v_profile.username,
    'avatar_id', v_profile.avatar_id,
    'is_me', v_profile.user_id = auth.uid(),
    'is_following', exists (
      select 1 from public.book_affinity_follows
      where follower_id = auth.uid() and followed_id = v_profile.user_id
    ),
    'followers_count', (
      select count(*) from public.book_affinity_follows where followed_id = v_profile.user_id
    ),
    'following_count', (
      select count(*) from public.book_affinity_follows where follower_id = v_profile.user_id
    ),
    'published_reading_count', (
      select count(*) from public.books
      where user_id = v_profile.user_id and is_public = true and status = 'reading'
    )
  );
end;
$$;

create or replace function public.book_affinity_follow_reader(p_username text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_target uuid;
  v_username text := lower(trim(coalesce(p_username, '')));
begin
  if auth.uid() is null then
    raise exception 'Debes iniciar sesión para seguir lectores.' using errcode = '42501';
  end if;

  select user_id into v_target
  from public.book_affinity_profiles
  where username_normalized = v_username;

  if v_target is null then
    raise exception 'No existe ningún lector con ese usuario.' using errcode = 'P0002';
  end if;

  if v_target = auth.uid() then
    raise exception 'No puedes seguirte a ti mismo.' using errcode = '22023';
  end if;

  insert into public.book_affinity_follows (follower_id, followed_id)
  values (auth.uid(), v_target)
  on conflict do nothing;

  return public.book_affinity_find_reader(v_username);
end;
$$;

create or replace function public.book_affinity_unfollow_reader(p_user_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Debes iniciar sesión.' using errcode = '42501';
  end if;

  delete from public.book_affinity_follows
  where follower_id = auth.uid() and followed_id = p_user_id;

  return found;
end;
$$;

create or replace function public.book_affinity_list_following()
returns table (
  user_id uuid,
  username text,
  avatar_id text,
  followed_at timestamptz,
  published_reading_count bigint
)
language sql
security definer
stable
set search_path = public
as $$
  select
    profile.user_id,
    profile.username,
    profile.avatar_id,
    follow.created_at,
    count(book.id) filter (where book.is_public = true and book.status = 'reading')
  from public.book_affinity_follows as follow
  join public.book_affinity_profiles as profile on profile.user_id = follow.followed_id
  left join public.books as book on book.user_id = profile.user_id
  where follow.follower_id = auth.uid()
  group by profile.user_id, profile.username, profile.avatar_id, follow.created_at
  order by lower(profile.username);
$$;

create or replace function public.book_affinity_list_followers()
returns table (
  user_id uuid,
  username text,
  avatar_id text,
  followed_at timestamptz,
  is_following_back boolean
)
language sql
security definer
stable
set search_path = public
as $$
  select
    profile.user_id,
    profile.username,
    profile.avatar_id,
    follow.created_at,
    exists (
      select 1 from public.book_affinity_follows as reciprocal
      where reciprocal.follower_id = auth.uid()
        and reciprocal.followed_id = profile.user_id
    )
  from public.book_affinity_follows as follow
  join public.book_affinity_profiles as profile on profile.user_id = follow.follower_id
  where follow.followed_id = auth.uid()
  order by lower(profile.username);
$$;

create or replace function public.book_affinity_social_feed()
returns table (
  id uuid,
  owner_user_id uuid,
  owner_username text,
  owner_avatar_id text,
  title text,
  subtitle text,
  authors text[],
  cover_url text,
  thumbnail_url text,
  categories text[],
  page_count integer,
  current_page integer,
  progress_percent numeric,
  status text,
  rating numeric,
  updated_at timestamptz,
  comments_count bigint
)
language sql
security definer
stable
set search_path = public
as $$
  select
    book.id,
    book.user_id,
    profile.username,
    profile.avatar_id,
    book.title,
    book.subtitle,
    book.authors,
    book.cover_url,
    book.thumbnail_url,
    book.categories,
    book.page_count,
    book.current_page,
    book.progress_percent,
    book.status,
    book.rating,
    book.updated_at,
    (select count(*) from public.book_affinity_comments as comment where comment.book_id = book.id)
  from public.book_affinity_follows as follow
  join public.book_affinity_profiles as profile on profile.user_id = follow.followed_id
  join public.books as book on book.user_id = follow.followed_id
  where follow.follower_id = auth.uid()
    and book.is_public = true
    and book.status = 'reading'
  order by book.updated_at desc;
$$;

create or replace function public.book_affinity_public_book(p_book_id uuid)
returns table (
  id uuid,
  user_id uuid,
  owner_username text,
  owner_avatar_id text,
  google_books_id text,
  title text,
  subtitle text,
  authors text[],
  description text,
  cover_url text,
  thumbnail_url text,
  isbn_10 text,
  isbn_13 text,
  publisher text,
  published_date text,
  language text,
  categories text[],
  page_count integer,
  current_page integer,
  progress_percent numeric,
  status text,
  rating numeric,
  started_at date,
  finished_at date,
  added_at timestamptz,
  updated_at timestamptz,
  is_public boolean
)
language sql
security definer
stable
set search_path = public
as $$
  select
    book.id,
    book.user_id,
    profile.username,
    profile.avatar_id,
    book.google_books_id,
    book.title,
    book.subtitle,
    book.authors,
    book.description,
    book.cover_url,
    book.thumbnail_url,
    book.isbn_10,
    book.isbn_13,
    book.publisher,
    book.published_date,
    book.language,
    book.categories,
    book.page_count,
    book.current_page,
    book.progress_percent,
    book.status,
    book.rating,
    book.started_at,
    book.finished_at,
    book.added_at,
    book.updated_at,
    book.is_public
  from public.books as book
  join public.book_affinity_profiles as profile on profile.user_id = book.user_id
  where book.id = p_book_id
    and public.book_affinity_can_view_published_book(book.id);
$$;

create or replace function public.book_affinity_book_comments(p_book_id uuid)
returns table (
  id bigint,
  user_id uuid,
  username text,
  avatar_id text,
  body text,
  created_at timestamptz,
  can_delete boolean
)
language sql
security definer
stable
set search_path = public
as $$
  select
    comment.id,
    comment.user_id,
    coalesce(profile.username, 'lector'),
    profile.avatar_id,
    comment.body,
    comment.created_at,
    comment.user_id = auth.uid() or book.user_id = auth.uid()
  from public.book_affinity_comments as comment
  join public.books as book on book.id = comment.book_id
  left join public.book_affinity_profiles as profile on profile.user_id = comment.user_id
  where comment.book_id = p_book_id
    and public.book_affinity_can_view_published_book(p_book_id)
  order by comment.created_at asc;
$$;

create or replace function public.book_affinity_add_comment(p_book_id uuid, p_body text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_body text := trim(coalesce(p_body, ''));
  v_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Debes iniciar sesión para comentar.' using errcode = '42501';
  end if;

  if not public.book_affinity_can_view_published_book(p_book_id) then
    raise exception 'No puedes comentar este libro privado.' using errcode = '42501';
  end if;

  if char_length(v_body) not between 1 and 1000 then
    raise exception 'El comentario debe tener entre 1 y 1000 caracteres.' using errcode = '22023';
  end if;

  insert into public.book_affinity_comments (book_id, user_id, body)
  values (p_book_id, auth.uid(), v_body)
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.book_affinity_delete_comment(p_comment_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Debes iniciar sesión.' using errcode = '42501';
  end if;

  delete from public.book_affinity_comments as comment
  using public.books as book
  where comment.id = p_comment_id
    and book.id = comment.book_id
    and (comment.user_id = auth.uid() or book.user_id = auth.uid());

  return found;
end;
$$;

revoke all on function public.book_affinity_can_view_published_book(uuid) from public;
revoke all on function public.book_affinity_set_my_avatar(text) from public;
revoke all on function public.book_affinity_find_reader(text) from public;
revoke all on function public.book_affinity_follow_reader(text) from public;
revoke all on function public.book_affinity_unfollow_reader(uuid) from public;
revoke all on function public.book_affinity_list_following() from public;
revoke all on function public.book_affinity_list_followers() from public;
revoke all on function public.book_affinity_social_feed() from public;
revoke all on function public.book_affinity_public_book(uuid) from public;
revoke all on function public.book_affinity_book_comments(uuid) from public;
revoke all on function public.book_affinity_add_comment(uuid, text) from public;
revoke all on function public.book_affinity_delete_comment(bigint) from public;

grant execute on function public.book_affinity_set_my_avatar(text) to authenticated;
grant execute on function public.book_affinity_find_reader(text) to authenticated;
grant execute on function public.book_affinity_follow_reader(text) to authenticated;
grant execute on function public.book_affinity_unfollow_reader(uuid) to authenticated;
grant execute on function public.book_affinity_list_following() to authenticated;
grant execute on function public.book_affinity_list_followers() to authenticated;
grant execute on function public.book_affinity_social_feed() to authenticated;
grant execute on function public.book_affinity_public_book(uuid) to authenticated;
grant execute on function public.book_affinity_book_comments(uuid) to authenticated;
grant execute on function public.book_affinity_add_comment(uuid, text) to authenticated;
grant execute on function public.book_affinity_delete_comment(bigint) to authenticated;

comment on column public.books.is_public is 'Permite mostrar la ficha social a los seguidores del propietario.';
comment on table public.book_affinity_follows is 'Relaciones de seguimiento entre lectores de Book Affinity.';
comment on table public.book_affinity_comments is 'Comentarios asociados únicamente a libros publicados.';
